apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-test
  template:
    metadata:
      labels:
        app: api-test
        admission-webhook: enabled
    spec:
      containers:
      - name: api-test
        image: herrmann89/api-test:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health-check
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /health-check
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 5
      imagePullSecrets:
      - name: dockerhub
