replicaCount: 1

image:
  repository: herrmann89
  pullPolicy: IfNotPresent
  tag: admission-webhook:latest

imagePullSecrets:
- name: dockerhub


serviceAccount:
  create: true
  annotations: {}
  name: "admission-webhook"

secret:
  name: admission-webhook-tls
  tlscrt: xxx
  tlskey: xxx


args:
- "/etc/opt/tls.crt"
- "/etc/opt/tls.key"
- "8443"

volumes:
  name: cert
  secretName: simple-kubernetes-webhook-tls
  mount: /etc/opt
  readOnly: true

configmap:
   name: configvalues
   mount: /data/config

podAnnotations: {}

podSecurityContext: {}

SecurityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 2000

  service:
    type: Loadbalancer
    port: 8080
  
  resources:

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}